### ISSUE TITLE
Generate PlantUML for Visual Studio Code

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#111]
...it's a quick solution for the moment as we need an extra vsc extension to view uml diagrams, but it works...

![screen shot 2017-02-25 at 12 59 33](https://cloud.githubusercontent.com/assets/629760/23330864/7b9e746a-fb5a-11e6-9e3e-d58a01eb6f69.png)

**Comment by colameo** [comment]
@cbornet @jbadeau we should plan to have soon a release 1.1.x with a set of available features.
let's make a final list of features we want to deliver.

**Comment by cbornet** [comment]
@colameo this is totally awesome !! I can't wait !

**Comment by cbornet** [comment]
@colameo maybe create a ticket with a TODO for the 1.1 release ?

**Comment by jbadeau** [comment]
Wow cool

**Comment by PierreBesson** [comment]
Wow this is extremely cool. I can't wait to try it !

**Comment by colameo** [comment]
For the moment everything is handled by the backend. Even rendering a JDL to PlantUML is done on the server side, which produces an image file (png) of the UML model. I also defined a shortcut ("ALT + D") to preview a diagram of an JDL model.

**Comment by cbornet** [comment]
Trying that ASAP ! 💯

**Comment by PierreBesson** [comment]
@cbornet if you have the time, could you publish the extension to the store. I tried to run it from the sources but it didn't work.

**Comment by colameo** [comment]
...pls wait with publishing. I can send you a link & infos how to install it from source. We should first test it properly. However, the 1.1.0 release is not yet done...

**Comment by colameo** [comment]
see also https://github.com/Microsoft/vscode/issues/22783#issuecomment-287316062

**Comment by colameo** [comment]
...[here](https://www.dropbox.com/s/dziakmix6sxj799/jdl-1.1.0.vsix?dl=0) an extension preview
to install it from the shell:
$ code --install-extension ./jdl-1.1.0.vsix

As I said we are near to finish (you may want to have a look to our [planning](https://github.com/jhipster/jhipster-ide/projects/2)).
