### ISSUE TITLE
Enhance JDL grammar to fullfil requirements (see JDL official page)

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#115]
1) Add TextBlob to the blob types
AnyBlob or just Blob to create a field of the “any” binary type;
ImageBlob to create a field meant to be an image.
TextBlob to create a field for a CLOB (long text).

2) Commas are optional:
So let's make them optional in the grammar.

3) Enhance comment definitions to be used as JavaDoc.
// an ignored comment
/** not an ignored comment */ => JavaDoc

4) Change renderer / generators to handle the above stuff

...I've already started with this issue => feature/serano/jdl_enhancement

**Comment by colameo** [comment]
finished except step 4 (see #118)

**Comment by MathieuAA** [comment]
@colameo Hello! Are you gonna need something after the application generation is done? The grammar is finished (minus some unforeseen fixes/modifications).
