### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#116]
- Finish all [release issues](https://github.com/jhipster/jhipster-ide/projects/2)
- Build & release
- Create release notes
- Publish to Eclipse Marketplace
- Publish to VS Code Marketplace

**Comment by jdubois** [comment]
And please notify me so I tweet about it with the JHipster account :-)

**Comment by colameo** [comment]
@jdubois will do - thanks!

**Comment by colameo** [comment]
JHipster IDE 1.1.0 is released and available from eclipse and vsc marketplaces.
Installation guide are not yet up-to-date (will do next week). To install under vsc search for **jhipster** extension. The old extension is still available under **jdl** (@cbornet can you remove it?).

**Comment by cbornet** [comment]
👏

**Comment by jdubois** [comment]
Great work guys!!!! Can you tell me when you update the documentation at https://jhipster.github.io/jhipster-ide/ ? That will be easier for everyone to use!
I'll try to use this next week at Devoxx France during my conference
