### ISSUE TITLE
TextBlob not supported

### ISSUE THREAD

**Issue by s-t-x** [jhipster/jhipster-ide#120]
Not all of JDL syntax is supported, apparently. Notably, TextBlob field is not recognized.

```
Couldn't resolve reference to JdlEnum 'TextBlob'.	Model.jdl	/bSurveyJDL/src/model	line: 100 /bSurveyJDL/src/model/Model.jdl	JDL Problem
```

The problem is gone if I put Blob instead.

**Comment by colameo** [comment]
this issue is fixed and will be delivered in the next release 1.1.0 (see https://github.com/jhipster/jhipster-ide/issues/115)
