### ISSUE TITLE
JDL Isn't Working on Visual Studio

### ISSUE THREAD

**Issue by vw98075** [jhipster/jhipster-ide#144]
After running PlantUML according the instruction on https://jhipster.github.io/jhipster-ide/ , I get an error "Image file .png not found!"

**Comment by vw98075** [comment]
When will it be fixed?

**Comment by jdubois** [comment]
Please don't stress the team. It's OSS, there is no deadline.

**Comment by jbadeau** [comment]
Hello,
I'm sorry that the ide doesn't work for you. If you could post the stacktrace we will investigate and try to resolve the issues asap.

**Comment by vw98075** [comment]
I only get my hand on Visual Studio for this task. I will look into stacktrace as I don't know where I can find it yet. BTW, I am not the only person have this problem. I posted my problem in the online chat room. Jon Ruddell had verified the problem. He said that he didn't know the cause.

**Comment by vw98075** [comment]
I find the executable file, but don't know where are the rest of files nor how to obtain a log file.

**Comment by jbadeau** [comment]
What version of visual studio code are u using?

**Comment by vw98075** [comment]
The latest one.

**Comment by colameo** [comment]
The png file is generated on the backend (LSP server) and sometimes (we have to investigate why) it takes quit a long time. BTW, the png file is generated every time you change + save the JDL file. The actual implementation of the VSC extension is unstable and we have to work on it. Also the amount of features available are just a small subset as in eclipse.

**Comment by vw98075** [comment]
To my understanding, I need to generate a whole project to have a class diagram. That is the reason I want to use Visual Studio so that I have a clear look at relationships of classes.

**Comment by ShiJunXia123** [comment]
Maybe you computer need to configure the Java environment! @vw98075 O(∩_∩)O

**Comment by jbadeau** [comment]
A JDL file does not need a full jhipster project to be viewed but you need at least a project folder in an eclipse workspace to open the file
