### ISSUE TITLE
eclipse neon 3

### ISSUE THREAD

**Issue by sg02** [jhipster/jhipster-ide#145]
When I create a new JDL project, got an error message like 'Error: org.eclipse.xtend2.lib.StringConcatenation.append(LJava/lang/String;)V'.

![capture](https://user-images.githubusercontent.com/25279931/27314461-10233f2c-55af-11e7-8054-66ab682acdf8.PNG)

What do I need to do for it?

**Comment by colameo** [comment]
Did you install ALL features of the update site? 
Please post the stacktrace (open Show View -> Error Log).

**Comment by sg02** [comment]
![image](https://user-images.githubusercontent.com/25279931/27521203-0832b9f0-5a55-11e7-9dbf-55de78dfe037.png)

I installed All features of the update, I think. And here is Error Log.

**Comment by colameo** [comment]
not reproducable

**Comment by colameo** [comment]
please reopen with more information how to reproduce, thanks!
