### ISSUE TITLE
[Eclipse] 'path' variable should points to "project path" instead of "workspace path"

### ISSUE THREAD

**Issue by xdworkshop** [jhipster/jhipster-ide#147]
When you don't use the default location in Jhipster new Project Creation, jdl file are generated in the project path (that is correct), but yeoman script is lauch in the workspace dir so all the files are generated  in the workspace path (that is not correct: the shell script should use project location).

**Comment by colameo** [comment]
could not reproduce: 
![jh-path](https://user-images.githubusercontent.com/629760/29749151-23784eda-8b26-11e7-91ca-a4d0d4876f5c.png)

print your variables by putting an echo statement in the Script window in the JHipster preference page like this and check again:

![jh-prefs](https://user-images.githubusercontent.com/629760/29749177-74d335a6-8b26-11e7-8561-0c7b745390b7.png)

please let me also know:
- OS (Win, Mac, Linux)
- Eclipse version
- Paste your Shell snippet here

reopen this issue again if you can reproduce it.

**Comment by colameo** [comment]
...and please try always with a fresh installation of eclipse ;-)
