### ISSUE TITLE
Migrate to xcore

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-ide#16]
DOD
- migrate inferred ecore model to xcore

**Comment by colameo** [comment]
Jose, I do not thing this would bring a big advantage. Please also be aware, that this would make language enhancements a bit harder to implement. I would say, let's see if we need it and do it once the grammar is stable enough - just my opinion... ;-)

**Comment by jbadeau** [comment]
Yes, I agree.

**Comment by colameo** [comment]
not needed
