### ISSUE TITLE
Update marketplace with JDL

### ISSUE THREAD

**Issue by paulvi** [jhipster/jhipster-ide#162]
Eclipse can automatically find and suggest to install plugins to work with specific files.

For example https://marketplace.eclipse.org/content/jenkins-editor has tag `fileExtension_Jenkinsfile`, so any user opening `Jenkinsfile` will get suggestion to install Jenkins Editor.

Please update https://marketplace.eclipse.org/content/jhipster-ide entry  to add tag `fileExtension_jdl`

**Comment by colameo** [comment]
that's a good idea! I guess we need to support "jdl" and "jh" as well.
