### ISSUE TITLE
jdot pragma does not render relationships properly

### ISSUE THREAD

**Issue by capital5** [jhipster/jhipster-ide#164]
When "!pragma graphviz_dot jdot" is included in the plantuml source, the rendering is incorrect.

If the same pragma is removed, the diagram is rendered properly.

I used the default jhipster project to test this on a mac.

**Comment by colameo** [comment]
This is a known limitation. The jdot / plantuml integration is on alpha stage. If this matters to you, please install the graphviz package. In the meantime I will contact the plantuml team and figure out if there is workaround to this issue.
