### ISSUE TITLE
[Eclipse] Support CodeMining for JDL Editor

### ISSUE THREAD

**Issue by angelozerr** [jhipster/jhipster-ide#172]
Eclipse Photon will provide CodeMining feature (CodeLens) https://www.eclipse.org/eclipse/news/4.8/M5/#Platform-Dev

It should be cool if JDL Editor could consume it to display for instance before entity name the number of references of this entity.

I have started this feature 'number of references' for JDT Java Editor https://github.com/angelozerr/jdt-codemining.

If you need help for this feature, don't hesitate to tell me.

**Comment by angelozerr** [comment]
> I'll keep this issue open but with a low priority.

Yes sure I understand, I wanted just to share with you about CodeMing feature which is available for Photon.

A another nice idea is that you provide a JDL Language Server where you implement CodeLens. The benefit with that is it will work with VSCode and Eclipse (thanks to LSP4e which consumes LSP CodeLens with Photon CodeMining)

**Comment by colameo** [comment]
We have already a LSP server for JDL and an extension for VSCode which is based on that.

**Comment by angelozerr** [comment]
> We have already a LSP server for JDL and an extension for VSCode which is based on that.

Oh great! So you could consume lsp4e for that and even https://github.com/eclipse/tm4e to consume the textmate https://github.com/jhipster/jhipster-ide/blob/master/jdl/io.github.jhipster.jdl.vscode/syntaxes/jdl.tmLanguage

**Comment by colameo** [comment]
Your comments are not related to this issue and we do not want to misuse github as chat/forum system. I'm going to lock this conversation.

**Comment by jbadeau** [comment]
We always welcome feature requests. Can you open a new issue. We don’t have a slack or hitter yet do I guess we should create one ;)
