### ISSUE TITLE
Can not generate a new project in Eclipse

### ISSUE THREAD

**Issue by crowne** [jhipster/jhipster-ide#178]
I am using the following eclipse on Windows 10:

> Spring Tool Suite 
> Version: 3.9.2.RELEASE
> Build Id: 201712210947
> Platform: Eclipse Oxygen.2 (4.7.2)

I have installed JHipster using Yarn as recommended by https://www.jhipster.tech/installation/
I have installed JHipster-IDE via the ecipse market place.
When I try to generate a new project I get the following error:

> Initialize JHipster project TestProject
> Error jhipster
> 
> You don't seem to have a generator with the name “jhipster” installed.
> But help is on the way:
> 
> You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
> Install them with npm install generator-jhipster.
> 
> To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.
> 
> If yo cannot find the generator, run yo doctor to troubleshoot your system.
> Yeoman JHipster generator is required but it's not installed!
> 'mvnw.cmd' is not recognized as an internal or external command,
> operable program or batch file.
> maven wrapper script not found!
>

**Comment by jdubois** [comment]
If you have this error then JHipster isn't installed, or at least it's not
in your path

**Comment by colameo** [comment]
you need to adapt in the eclipse preference page the shell integration:

![win10__running_](https://user-images.githubusercontent.com/629760/38144481-29095b0a-3445-11e8-9500-8a3b20077ec0.jpg)

**Comment by colameo** [comment]
...and btw, thanks for reporting! I will adapt that for the next release

**Comment by crowne** [comment]
Removing yo from the shell integration fixed it ... thanks Serano!
