### ISSUE TITLE
Propose graphical rendering solution for JDL

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-ide#18]
The current JDL studio provides a graphical representation of a JDL file. It would be nice to provide an IDE based equivalent. Some options are:
- graphiti
- sirius
- kieler
- Poseidon

**Comment by jbadeau** [comment]
Will use Sirius as it seems the easiest to use for or requirements

**Comment by colameo** [comment]
I guess you just want to have a graphical viewer for JDL and not a graphical editor right?

**Comment by colameo** [comment]
...a viewer only solution could be implemented in a few days.

**Comment by jbadeau** [comment]
@colameo yes, its just to provide the view like they have in jdl-studio. I had a look at sirius and it looks pretty simple. Would you rather use another framework than sirius?

**Comment by colameo** [comment]
if you just want a viewer, I can do it similar to JDL studio. I know at least 3 possible products (but I've to figure out which one fits as best)... shall I take this task over?

**Comment by jbadeau** [comment]
Sure, if you like. I will work on https://github.com/jbadeau/jdl/issues/3 and https://github.com/jbadeau/jdl/issues/13 after the move to jhipster org.

**Comment by colameo** [comment]
![screen shot 2016-10-03 at 14 46 06](https://cloud.githubusercontent.com/assets/629760/19037766/500fb7d6-8978-11e6-9c40-377862805926.png)

**Comment by colameo** [comment]
...not yet done, but just as a preview ;-)

**Comment by jbadeau** [comment]
@colameo Cool! What framework is that. Can you customize the look and feel?

**Comment by colameo** [comment]
The framework is called PlantUML and it is possible to customize the look & feel

**Comment by jbadeau** [comment]
Was looking at Plant UML and it looks pretty interesting.

My thoughts:

pros
1. plant uml is cross platform so it could probably be used to provide a solution for intellij too and the web it seems
2. there is support for skinning diagrams (but not for their views)
3. the api looks pretty straight forward

cons
1. it's not available under the normal eclipse update site
2. it has an external dependency to graphviz  binaries which has not had a mac release in quite some time. http://www.graphviz.org/Download_macos.php and you need to run command line tools to get it to work on newer versions
3. I really would prefer to keep the install simple
4. the plantui (icons, views, etc) look pretty dated and not very user friendly
5. the default diagram styling is also pretty dated and looks out of place with eclipse

**Comment by cbornet** [comment]
pros: there seem to be a vscode extension for it

**Comment by colameo** [comment]
...ok, this was just a quick 1st try :-) of course there are other solutions, but not so quick as with plant
