### ISSUE TITLE
Add support for Apache Netbeans

### ISSUE THREAD

**Issue by DanielFran** [jhipster/jhipster-ide#180]
Is there possibility to create plugin for Apache NetBeans ?

**Comment by jbadeau** [comment]
If netbeans add support for LSP then it would be pretty easy. 

https://issues.apache.org/jira/plugins/servlet/mobile#issue/NETBEANS-180

Not a lot of activity on the issue

**Comment by colameo** [comment]
...well from the experience with the Visual Studio Code extension, we would also need to add syntax highlighting and shortcuts, integrate with PlantUML, build and package everything as a NetBeans plugin, test it, make it available to the NetBeans plugins repository etc. So, I would estimate an effort of about 10-15 days. Before doing that I would first analyse how many JHipsters are really using NetBeans to develop applications.
