### ISSUE TITLE
Error on new syntax of pattern attribute

### ISSUE THREAD

**Issue by crowne** [jhipster/jhipster-ide#181]
Using the JHipster IDE in Eclipse I get a parsing error when specifying a pattern on a field of an entity, example JDL shown below.

> mismatched input '/' expecting RULE_STRING	Model.jdl line: 9 JDL Problem
> missing EOF at '/'	                        Model.jdl line: 9 JDL Problem
> no viable alternative at input '-'			Model.jdl line: 9 JDL Problem
> no viable alternative at input ']'			Model.jdl line: 9 JDL Problem

The parsing error also seems to stop the PlantUML rendering.

My JHipster version is 4.14.1
From the jdl [docs](https://www.jhipster.tech/jdl/#entitydeclaration)

> Regexes are a bit special as they are used like this (from v1.3.6):
> 
> entity A {
>   myString String required minlength(1) maxlength(42) pattern(/[A-Z]+/)
> }
> If you’re using the generator prior to v4.9.X, you’d need to use patterns like this pattern('[A-Z]+').
> 

When I change the jdl to use the quoted syntax instead of the forward slashes, then I get a failure when I try to run _jhipster import-jdl_.

`
LEN_CCY = 3
LEN_CTRY = 2

entity Currency {
	/** ISO 4217 */
	cd			String required minlength(LEN_CCY) maxlength(LEN_CCY) pattern(/[A-Z]{3}/),
	name		String required maxlength(80),
	decimals	Integer required
}

entity Country {
	/** ISO 3166-2 */
	cd			String required minlength(LEN_CTRY) maxlength(LEN_CTRY) pattern(/[A-Z]{2}/),
	name		String required maxlength(80)
}

relationship ManyToOne {
	Country{localCurrencyCd(cd)} to Currency
}
`

**Comment by colameo** [comment]
Thanks for reporting - looks like a bug.

Which version of the JHipster IDE do you use?

**Comment by colameo** [comment]
in the latest available plugin we support only the quoted pattern('[A-Z]+') variant.
However, I just tried with this pattern('/[A-Z]+/') (I've also 4.14.1 installed) and it works.

This example works for me:
entity Client {
  nome String required pattern('/[A-Z]+/')
  email String
}

dto * with mapstruct

// Set service options to all except few
service all with serviceImpl

So, looks like the example in the JDL documentation is wrong...

**Comment by crowne** [comment]
Thanks that works for me too.
I am using Hipster IDE 1.3.1

**Comment by bd82** [comment]
@MathieuAA as long as the pattern has the forward slashes delimiters it is easy to identify.

**Comment by MathieuAA** [comment]
Okay, I'm fixing the grammar in the master branch right now.

**Comment by MathieuAA** [comment]
@bd82 I'll create an issue for this in JHipster Core... this may be problematic.

**Comment by bd82** [comment]
@MathieuAA I don't understand why it should be problematic  but let me know if any help is required...
