### ISSUE TITLE
not getting react js as option for ui when using eclipse plugin for jhipster

### ISSUE THREAD

**Issue by vikrantch-hk** [jhipster/jhipster-ide#187]
hi team, I am not seeing react for ui option when using jhipster eclipse plugin, is this yet to be introduced.

I am using jhipster ide 1.3.1 plugin

**Comment by colameo** [comment]
if you mean the application JDL extension:
`
application { 
    config { 
      clientFramework react 
      ...
    } 
}
`

yes, it's implemented but no yet released.

middle/end of June is the release date for v1.4.0.
