### ISSUE TITLE
Migration to the JHipster organization

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-ide#21]
@jbadeau @colameo I've invited you to the JHispter organization on GitHub, and created a specific team for you.

If you still want to migrate you project to JHipster (nothing forced, you can change your mind):

- Can you transfer the project to me ("jdubois"), as I don't think you can transfer it directly to an organization (but if you can, just do it..) ?
- I will then transfer it to the JHipster organization
- I will rename it to "jhipster/jhipster-ide"
- I will give your team admin access to the repo, but the other JHipster members won't have access to it -> it's still your repo, you can then invite people to it, if you want to

**Comment by jbadeau** [comment]
@colameo can you transfer the repo after your done with #23?

**Comment by colameo** [comment]
@jbadeau yes, if you give me admin rights ;-)
see https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

**Comment by jbadeau** [comment]
@jdubois I made a request to transfer to your account. I cannot transfer to jhipster without being an admin.

**Comment by jdubois** [comment]
Migration complete, @jbadeau you should be admin, with @colameo ->ping me if you see an issue

**Comment by jdubois** [comment]
Sorry I called it "jdl-ide" and not "jhipster-ide", so I renamed it...

**Comment by jbadeau** [comment]
moved to jhipster org and renamed to jhipster-ide
