### ISSUE TITLE
"Constraint 'required' on a relationship of type OneToMany will be ignored" message doesn't seem accurate.

### ISSUE THREAD

**Issue by RPrimrose** [jhipster/jhipster-ide#216]
If I have JDL like 
```
entity Example1 
entity Example2

relationship OneToMany {
    Example1 to Example2{something required}
}
```
then a warning will be shown saying `Constraint 'required' on a relationship of type OneToMany will be ignored`

However if I remove the `required` keyword and import the JDL then the generated code has several differences.

For example, the `something_id` field in the Liquibase change set will become nullable and the @NotNull attribute will be removed from the `something` field in the Example2 domain object.

I'm not sure if this is a bug in this plugin or is a bug in the actual JHipster JDL import code.

**Comment by colameo** [comment]
@jdubois @MathieuAA how is this case treated in the generator? I can remember when I added this validation to the IDE it came from a discussion we had around multiplicity in relationships... however, I can of course remove this "warning" if it's not justified.

**Comment by jdubois** [comment]
For me we only have `required` fields for ManyToOne, and nothing for OneToMany. @RPrimrose can you provide a complete JDL, so we can test?

**Comment by RPrimrose** [comment]
@jdubois sure, the JDL I've got above is literally enough to reproduce this :) 

To replicate:
1. Create an empty folder, run `jhipster`, accept all defaults
2. Copy JDL from my first post into `example.jdl`, run `jhipster import-jdl example.jdl`
3. Have a look at the Example2.java file, note the @NotNull annotation on `private Example1 something;`
4. Modify the JDL to remove `required`, rerun `jhipster import-jdl example.jdl`. You'll get prompted to overwrite various files. Accept them changes. Have a look at Example2.java and see that the @NotNull annotation has been removed.

(I'm on JHipster 5.1.0, in case that makes a difference)

**Comment by RPrimrose** [comment]
Yeah, I'm happy with the generated code and the behaviour makes sense to me, so I suspect this is a spurious warning. My main worry would be if the warning is valid and I'm relying on an undefined behaviour that might go away in a future version of JHipster.

**Comment by jdubois** [comment]
@RPrimrose no we don't touch that part much, it's highly complex and it has proven to be very stable, so nobody dares to update it anymore :-)
I think the warning can be removed, then I need to check if we change something in the CLI, maybe it's not possible (it can't describe stuff as well as the JDL).

**Comment by colameo** [comment]
ok, guys, thanks for the clarification. I will remove this warning in the next release v1.5.0.

**Comment by colameo** [comment]
fixed
