### ISSUE TITLE
Vscode plugin issues

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-ide#219]
The vscode plugin has a typo in the default value for 'protractor'. The current values suggested are `[protactor, cucumber, gatling]` since the value is validated against `protactor` it fails. 

![image](https://user-images.githubusercontent.com/1107223/45598546-16ba8180-b9de-11e8-8357-7555840cf0b9.png)

**Comment by deepu105** [comment]
Also it doesnt accept the below, but its a valid case for mongodb

![image](https://user-images.githubusercontent.com/1107223/45598556-48cbe380-b9de-11e8-9e87-b7799dffc769.png)

**Comment by colameo** [comment]
> Also, it doesn't accept the below, but its a valid case for mongodb, probably the behavior is same for cassandra and couchbase as well.
> 
> ![image](https://user-images.githubusercontent.com/1107223/45598556-48cbe380-b9de-11e8-9e87-b7799dffc769.png)

...hm, strange, either the documentation is also wrong or I miss here something:

<img width="799" alt="screen shot 2018-09-17 at 08 24 55" src="https://user-images.githubusercontent.com/629760/45608460-422b8380-ba53-11e8-8a72-625668158449.png">
<img width="697" alt="screen shot 2018-09-17 at 08 25 03" src="https://user-images.githubusercontent.com/629760/45608461-422b8380-ba53-11e8-8640-ab9b1b020d3a.png">

**Comment by colameo** [comment]
> The vscode plugin has a typo in the default value for 'protractor'. The current values suggested are `[protactor, cucumber, gatling]` since the value is validated against `protactor` it fails.
> 
> ![image](https://user-images.githubusercontent.com/1107223/45598546-16ba8180-b9de-11e8-8357-7555840cf0b9.png)

...and the value **protactor** comes also from the jdl documentation:

<img width="754" alt="screen shot 2018-09-17 at 08 33 43" src="https://user-images.githubusercontent.com/629760/45608663-70f62980-ba54-11e8-8180-0af4f95a433a.png">
