### ISSUE TITLE
vs code internal server error

### ISSUE THREAD

**Issue by PhlppKnst** [jhipster/jhipster-ide#232]
Hi,
I use the jhipster extension in vs code on windows 10.
It did work before, but for several weeks now, every time when I save the jdl to render the .png 'internal server error' is only shown and no .png is produced.
I already tried to debug the extension, but with no luck. 
I get 
rejected promise not handled within 1 second

It comes from the extensionLauncher of vscode.
It is hard to tell whats the reason for this, but it could maybe server call for rendering the png.

Best,
Phlpp

**Comment by colameo** [comment]
Hi Phipp,
thanks for reporting this!

I presume you followed the installation instruction of JHipster and have also JDK installed on your machine, right?

Have you also installed [Graphviz](https://www.graphviz.org )?

/Serano

**Comment by colameo** [comment]
...please check also that your model is valid (has no error markers in the editor).

**Comment by colameo** [comment]
I confirm that it's not working on windows OS. I also found the problem and solution.
Will be fixed in v1.5.0
