### ISSUE TITLE
vscode JDL syntax validation

### ISSUE THREAD

**Issue by rubensa** [jhipster/jhipster-ide#236]
Using latest available Jhipster JDL vscode extension (**1.4.1**).
There are lot of syntax complains case seems that syntax validation is not aligned with current generator-jhipster vervion (**5.5.0**).
Most of them seems to be fixed for version 1.5.0 (#216, #219) or are already reported (#234, #235) but there seems to be one not reported yet.

Empty brackets gives a syntax error (but it's allowed, as can be specified for some application options).
![screenshot from 2018-10-19 12-59-39](https://user-images.githubusercontent.com/1469340/47214676-027ff080-d39f-11e8-93f7-deaf873359e4.png)

If some value is provided (and selected from completion helper) the error message is:
![screenshot from 2018-10-19 13-10-50](https://user-images.githubusercontent.com/1469340/47215142-a6b66700-d3a0-11e8-925b-bb4303d52f91.png)

**NOTE**:  Related with this...  the suggested values are not aligned with those specified in [Doc](https://www.jhipster.tech/jdl/#application_options):
![screenshot from 2018-10-19 13-11-21](https://user-images.githubusercontent.com/1469340/47215223-f39a3d80-d3a0-11e8-824d-b9eb35a10861.png)

Should be: protractor, cucumber, gatling

In general... IDE syntax and option values validation should be aligned with latest jhipster version (assuming published doc is aligned with latest jhipster version).

**Comment by colameo** [comment]
most of the above issues are solved and some will be fixed in v1.5.0 which will be released soon
