### ISSUE TITLE
No changelog for vscode extension

### ISSUE THREAD

**Issue by rubensa** [jhipster/jhipster-ide#242]
Since **v1.3.1** there is **no changelog** for JHipster JDL vscode extension.
![screenshot from 2018-10-23 09-52-37](https://user-images.githubusercontent.com/1469340/47344777-87258400-d6a9-11e8-900a-cb7db7537a30.png)

**Comment by colameo** [comment]
...I forgot to add the link, but just go to the project page if you are interested in what I've changed.
