### ISSUE TITLE
support references to objects in other files 

### ISSUE THREAD

**Issue by drummer3333** [jhipster/jhipster-ide#252]
Our model becomes a bit bigger and we want to split the JDL in multiple files. 
But I need to reference entities and enums from other files. When I do that, the jHipster IDE outputs errors and Plant UML Diagramm can't render anything.
Is it possible to refrence or import objects from other files?

I found only this related issue, but nothing with a real answer.
https://github.com/jhipster/jhipster-core/issues/170

**Comment by colameo** [comment]
Not supported at the moment but I can add this feature for the next release.

**Comment by colameo** [comment]
Done (but need to build a release to make it available and that takes more time)
