### ISSUE TITLE
How to create a new Model

### ISSUE THREAD

**Issue by amatosolivo** [jhipster/jhipster-ide#257]
Ones the JDL Pluggin for VSCode is installed how to create a new model

**Comment by colameo** [comment]
Presuming you've installed everything (jhipster, vscode and jhipster extension etc.).
For creating a new app:
- `mkdir <app-folder>`
- `cd <app-folder>`
- `code .`
- in vscode sidebar create a new file and named it `<app-or-whatever-name>.jdl`:
![jhcode](https://user-images.githubusercontent.com/629760/52910091-cc8e4280-3292-11e9-9f75-63e10d4c1eac.png)
- vscode will open the JHipster editor automatically for you which will allow you to use the content assist:
![jheditor](https://user-images.githubusercontent.com/629760/52910128-50e0c580-3293-11e9-986d-e6f5ad2e5084.png)
 
I keep this issue open as a reminder to improve documentation pages.
