### ISSUE TITLE
Add support for negative values

### ISSUE THREAD

**Issue by pmverma** [jhipster/jhipster-ide#258]
Constant value with negative value is displaying as an error statement.
Adding a negative value in `min()` is also same.

Error screenshot,
![jdl](https://user-images.githubusercontent.com/5289123/53217232-ac40f800-3685-11e9-84b5-10ab3c5e33e6.png)

Entity generation is fine but the red color is annoying.
Sample screenshot IDE -> vscode
It would be nice if negative values are also supported as well.

**Comment by colameo** [comment]
thanks for reporting!
