### ISSUE TITLE
Realease of IntelliJ

### ISSUE THREAD

**Issue by mohsenr7596** [jhipster/jhipster-ide#274]
We waiting for intelliJ version

**Comment by colameo** [comment]
Yes, I know and you are not the only one... are you or your company willing to sponsor this feature?

**Comment by xinatcg** [comment]
I am thinking to create the Intellij custom language plugin for JDL. I found the hardest part should the `Lexer and Parser`. **Do we have existing or similar grammatical analysis document for JDL?**  the Intellij use the [JFlex](https://jflex.de/) with `bnf` file like these examples:
1. https://github.com/BashSupport/BashSupport/blob/master/src/com/ansorgit/plugins/bash/lang/lexer/bash.flex
2. https://github.com/JetBrains/intellij-sdk-docs/blob/master/code_samples/simple_language_plugin/src/main/java/org/intellij/sdk/language/Simple.bnf

**Comment by colameo** [comment]
I've a simpler solution to this. will finish it somewhen this year... and believe it's not done by *just rewriting* the grammar (JH IDE is more than that)!

**Comment by colameo** [comment]
here some screenshots:

<img width="689" alt="Screen Shot 2019-06-02 at 11 52 40" src="https://user-images.githubusercontent.com/629760/75616335-efaf2b80-5b4f-11ea-8487-0b5e7e07f5e5.png">

<img width="1440" alt="Screenshot 2020-03-01 at 00 07 52" src="https://user-images.githubusercontent.com/629760/75616408-c8a52980-5b50-11ea-8cf5-364d7fdc940a.png">

**Comment by xinatcg** [comment]
that's great, thanks.

**Comment by colameo** [comment]
> that's great, thanks. Yes, for IDE, it is not enough.
> But my current necessary required feature includes:
> 
> 1. auto-completion
> 2. find usage
> 3. file structure

...of course, all above features you mentioned (and more) are already included. As I said, an IDE is more than just a grammar for a language and there's more behind the scenes to consider. But hey, if you think you can do it somehow faster and you can manage all the feature changes by yourself, then go ahead. 😉

However, I will continue on my implementation and we may have somewhen more than one solution for IntelliJ users. :bowtie:

**Comment by colameo** [comment]
I'm making progress. I'm planning to make an alpha release of the first version for IntelliJ in a couple of weeks.

**Comment by colameo** [comment]
...starts looking better but still needs improvements before releasing the first version:

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/629760/77579367-7c909f00-6eda-11ea-9955-6db04d0cc2f3.png">

<img width="1404" alt="Screenshot 2020-03-25 at 21 11 59" src="https://user-images.githubusercontent.com/629760/77581136-74862e80-6edd-11ea-8db6-ef02c5f3b02f.png">

**Comment by colameo** [comment]
this implementation won't be part of this project.

**Comment by ducanh2110** [comment]
Hi @colameo , Can I ask why this implementation won't be part of this project and where will it be implemented?

**Comment by colameo** [comment]
> Hi @colameo , Can I ask why this implementation won't be part of this project and where will it be implemented?

...it will come in the future, but don't know when - I'm too busy with other projects. Maybe this winter during xmas or so ... will see. 

I'm locking this issue as I don't like to have "chats" in issues.
