### ISSUE TITLE
Ignore node_modules folder in Problems view

### ISSUE THREAD

**Issue by lucarota** [jhipster/jhipster-ide#284]
Hi,

I just installed this extension in vs code.
Now the Problems View lists jdl errors in node_modules folder.
How can I ignore node_modules folder from checking?

Thank you.

**Comment by colameo** [comment]
have you tried this:

https://stackoverflow.com/questions/33258543/how-can-i-exclude-a-directory-from-visual-studio-code-explore-tab

**Comment by colameo** [comment]
look also here:
https://www.jhipster.tech/configuring-ide-visual-studio-code/

i close this issue as it is not related to this project
