### ISSUE TITLE
Wierd warnings.

### ISSUE THREAD

**Issue by Nektototam** [jhipster/jhipster-ide#291]
Visual Studio Code latest version. 

All relationships are grouped. 
I marked with !!!! lines with the warning. 

relationship OneToMany{
!!!!  MealPlan{plans} to DayPlan{mealplans}
  DayPlan{dayparts} to DayPlanPart{dayplan}
  ShoppingListItem{fooditems} to FoodItem{shlists}
  Household{shopingLists(title)} to ShoppingList{shophousehold(title)}
  ShoppingList{items} to ShoppingListItem{shoppingLists}
  Profile{homehousehold(title)} to Household{owner(nickname)}
  Chef{housholderChef(title)} to  Household{chef(title)}
 }
relationship ManyToMany{
Profile{changedrecipe(title)} to Recipe{modified(nickname)}
!!!!!DayPlanPart{recipes(title)} to Recipe{deyPlanPart( title)} 
}
!!!!relationship ManyToOne {
  Recipe{box(title)} to RecipeBox{recipe(title)}
}

relationship OneToOne {
  Profile{user(login)} to User
  Customer{custprofile(nickname)} to Profile
   RecipeBox {boxowner(nickname)}  to Profile{recipesbox(title)} 
!!!!   Household{storeroom(title)} to Storeroom{ownHousehold(title)}   
   Chef{chefprofile(nickname)} to Profile
  }

**Comment by colameo** [comment]
Thanks for reporting! Indeed, it's an issue I'll fix in the next release.

In the meantime, if you want to get rid of the linting warnings just put at first line of your JDL file one of the following comment statements:

`// no-linting`

or

`// lint=false `

**Comment by Nektototam** [comment]
I can do it, but what about real problems, that  "occur sometimes"? :)

**Comment by colameo** [comment]
only "extra validations" added in the last release are disabled. errors like references to a non-existent type or enum or wrong config / deployment parameters etc. are still shown. However, you can also just ignore the above warnings as they are only "suggested improvements" and do not have any impact to generation...
