### ISSUE TITLE
Unable to create new project in Eclipse

### ISSUE THREAD

**Issue by pnpninja** [jhipster/jhipster-ide#316]
Whenever I try to create a new project in Eclipse, I get this error - 

`The selected wizard could not be started.
org/eclipse/lsp4j/TextDocumentPositionParams (occurred in io.github.jhipster.jdl.ui.JDLExecutableExtensionFactory)
org/eclipse/lsp4j/TextDocumentPositionParams`

**Comment by colameo** [comment]
Which Eclipse version are you using? Have you tried with 2019-09 (4.13)?

**Comment by pnpninja** [comment]
I reinstalled my eclipse and all my plug-ins. All good now

**Comment by colameo** [comment]
ok, gut
