### ISSUE TITLE
Local build failing

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-ide#32]
@colameo  The build is failing locally due to missing plantuml dependencies:

[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: io.github.jhipster.jdl.ui 1.0.0.qualifier
[ERROR]   Missing requirement: io.github.jhipster.jdl.ui 1.0.0.qualifier requires 'bundle net.sourceforge.plantuml.eclipse 1.1.8' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: io.github.jhipster.jdl:io.github.jhipster.jdl.ui:1.0.0-SNAPSHOT @ /Users/jbadeau/git/jhipster-ide/io.github.jhipster.jdl.ui/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To

**Comment by jbadeau** [comment]
@colameo are u able to build locally? do I need to do something?

**Comment by colameo** [comment]
I've just deleted my local maven repo, cloned from master and could build successfully with maven (see also travis ci on my PRs):
....
[INFO] --- tycho-p2-plugin:0.23.1:update-local-index (default-update-local-index) @ io.github.jhipster.jdl.ui.tests ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] io.github.jhipster.jdl.parent ...................... SUCCESS [  1.593 s]
[INFO] io.github.jhipster.jdl ............................. SUCCESS [01:10 min]
[INFO] io.github.jhipster.jdl.ide ......................... SUCCESS [  1.168 s]
[INFO] io.github.jhipster.jdl.ui .......................... SUCCESS [  4.990 s]
[INFO] io.github.jhipster.jdl.web ......................... SUCCESS [ 16.471 s]
[INFO] io.github.jhipster.jdl.target ...................... SUCCESS [  0.035 s]
[INFO] io.github.jhipster.jdl.feature ..................... SUCCESS [  0.251 s]
[INFO] io.github.jhipster.jdl.repository .................. SUCCESS [  1.441 s]
[INFO] io.github.jhipster.jdl.tests ....................... SUCCESS [  5.636 s]
[INFO] io.github.jhipster.jdl.ui.tests .................... SUCCESS [ 10.775 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:43 min
[INFO] Finished at: 2016-10-06T13:48:26+02:00
[INFO] Final Memory: 210M/1612M
[INFO] ------------------------------------------------------------------------

**Comment by colameo** [comment]
...BTW, it's anyway strange cause we use 1.1.7 and not 1.1.8 of plantuml plugin.

**Comment by jbadeau** [comment]
i deleted and recloned, fixed. No idea what was wrong :(
