### ISSUE TITLE
Cannot clone this repository (jhipster-ide)

### ISSUE THREAD

**Issue by crowne** [jhipster/jhipster-ide#322]
I have forked this repo and tried to clone my fork and also the main repo several times, however I keep getting the same error pasted below:

> PS E:\jhipster> git clone https://github.com/crowne/jhipster-ide.git
> Cloning into 'jhipster-ide'...
> remote: Enumerating objects: 497, done.
> remote: Counting objects: 100% (497/497), done.
> remote: Compressing objects: 100% (292/292), done.
> remote: Total 13685 (delta 286), reused 336 (delta 136), pack-reused 13188
> Receiving objects: 100% (13685/13685), 221.36 MiB | 1.38 MiB/s, done.
> Resolving deltas: 100% (7310/7310), done.
> error: unable to create file docs/https-::rawgit.com:jhipster:jhipster-core:master:lib:dsl:gen:grammar.html.webloc: Invalid argument
> Updating files: 100% (994/994), done.
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'
> 
> PS E:\jhipster> git clone https://github.com/jhipster/jhipster-ide.git
> Cloning into 'jhipster-ide'...
> remote: Enumerating objects: 497, done.
> remote: Counting objects: 100% (497/497), done.
> remote: Compressing objects: 100% (292/292), done.
> remote: Total 13685 (delta 286), reused 336 (delta 136), pack-reused 13188
> Receiving objects: 100% (13685/13685), 221.36 MiB | 1.05 MiB/s, done.
> Resolving deltas: 100% (7310/7310), done.
> error: unable to create file docs/https-::rawgit.com:jhipster:jhipster-core:master:lib:dsl:gen:grammar.html.webloc: Invalid argument
> Updating files: 100% (994/994), done.
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'
> 
> PS E:\jhipster>

**Comment by pascalgrimaud** [comment]
I don't have any problem to clone the project:

```
11:24:38 in ~/projects/jhipster 
➜ git clone git@github.com:jhipster/jhipster-ide.git                                                       
Clonage dans 'jhipster-ide'...
remote: Enumerating objects: 799, done.
remote: Counting objects: 100% (799/799), done.
remote: Compressing objects: 100% (460/460), done.
remote: Total 13987 (delta 447), reused 518 (delta 208), pack-reused 13188
Réception d'objets: 100% (13987/13987), 221.45 Mio | 11.18 Mio/s, fait.
Résolution des deltas: 100% (7471/7471), fait.

11:25:09 in ~/projects/jhipster took 24s 
➜ cd jhipster-ide          

11:25:35 in projects/jhipster/jhipster-ide on  master 
➜ l
total 80K
drwxr-xr-x  9 pgrimaud pgrimaud 4,0K janv. 13 11:25 .
drwxrwxr-x 36 pgrimaud pgrimaud 4,0K janv. 13 11:24 ..
-rw-r--r--  1 pgrimaud pgrimaud 2,1K janv. 13 11:25 azure-pipelines.yml
drwxr-xr-x  3 pgrimaud pgrimaud 4,0K janv. 13 11:25 docs
drwxr-xr-x  8 pgrimaud pgrimaud 4,0K janv. 13 11:25 .git
-rw-r--r--  1 pgrimaud pgrimaud  421 janv. 13 11:25 .gitignore
drwxr-xr-x 16 pgrimaud pgrimaud 4,0K janv. 13 11:25 jdl
drwxr-xr-x  3 pgrimaud pgrimaud 4,0K janv. 13 11:25 .mvn
-rwxr-xr-x  1 pgrimaud pgrimaud 9,9K janv. 13 11:25 mvnw
-rw-r--r--  1 pgrimaud pgrimaud 6,5K janv. 13 11:25 mvnw.cmd
-rw-r--r--  1 pgrimaud pgrimaud 1009 janv. 13 11:25 pom.xml
-rw-r--r--  1 pgrimaud pgrimaud  375 janv. 13 11:25 .project
-rw-r--r--  1 pgrimaud pgrimaud 1,7K janv. 13 11:25 README.md
drwxr-xr-x  5 pgrimaud pgrimaud 4,0K janv. 13 11:25 releng
drwxr-xr-x  2 pgrimaud pgrimaud 4,0K janv. 13 11:25 .settings
-rw-r--r--  1 pgrimaud pgrimaud  312 janv. 13 11:25 settings.xml
drwxr-xr-x  7 pgrimaud pgrimaud 4,0K janv. 13 11:25 xdocker

11:25:36 in projects/jhipster/jhipster-ide on  master
```

I use Ubuntu. And you are with Windows, maybe there is a difference.
Do you have a specific git configuration ?

**Comment by colameo** [comment]
...this issue happens only for windows users and I do not intend to change it as I needed it exactly as it is now. I'm closing this issue.

**Comment by crowne** [comment]
OK, thanks I had difficulty understanding the error message ... windows doesn't like the .webloc filename under /docs with the colons in the file name.

**Comment by colameo** [comment]
...just use a proper (for developers more suitable) shell. If you installed git for windows on your machine then there is also a "gitbash.exe" on the root folder which I would recommend you to use. The windows default command shell (cmd.exe) is just crap and not appropriate for a developer. I just tried on my virtualmachine running windows and it works:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/629760/72411202-af941500-376a-11ea-8edb-7dd0b442974e.png">

**Comment by colameo** [comment]
...ok, I should not work when I'm traveling early in the morning to work and without having before a coffee :-) issue still happens (also with git bash), so I will fix it!

**Comment by phanideep9** [comment]
@colameo I got the same error in ubuntu
