### ISSUE TITLE
Weird formatting of enums when exporting to UML diagram

### ISSUE THREAD

**Issue by gmarziou** [jhipster/jhipster-ide#323]
Hello,

I'm using 1.9.1 in VSCode and enums are strangely formatted in UML diagram:

![enums](https://user-images.githubusercontent.com/361007/70549295-3b1af480-1b74-11ea-9fd4-517753be2d00.png)

The JDL:

~~~
enum MyEnum {
    ONE, TWO
}
~~~

Thanks

**Comment by colameo** [comment]
thanks for reporting!
