### ISSUE TITLE
not able to install JHipster IDE in Ecpplise

### ISSUE THREAD

**Issue by kbaati** [jhipster/jhipster-ide#327]
Hi,
When I try to drag and drop JHipster IDE in eclipse, I have the following error: 
"The following solutions are not compatible with this version of Eclipse."
I'm using eclipse version: 2019-06 under windows system
the same problem with the version 2019-12 (4.14.0)

![image](https://user-images.githubusercontent.com/10740332/73592353-a4c2d980-44f9-11ea-8731-060430d19f82.png)

**Comment by colameo** [comment]
I've set the compatibility level to support also 2019-06. But be aware that the official eclipse version which is supported and also tested is **2019-09**. 

So, can you retry and let me know?

**Comment by colameo** [comment]
> **2019-09**.

... and **2019-12** should now also be available. Anyway, as I said, it's not test it ...
