### ISSUE TITLE
vscode jdl generates png broken, says cannot find Graphviz

### ISSUE THREAD

**Issue by gtyang** [jhipster/jhipster-ide#332]
The vscode extention broken suddenly.

![model](https://user-images.githubusercontent.com/1061022/75641210-70664880-5c72-11ea-83db-cb781e00b677.png)

Dot executable:  '/usr/bin/dot'
File does not exists
Cannot find Graphviz. You should try ....  

I found a tips of the extention, said that it crash many time, so ..., I cannot remember it clearly.

**Comment by colameo** [comment]
that means you do not have Graphviz installed or it cannot be found on your machine.

I guess you a have a unix machine so, open a shell and type "which dot"

```
$ which dot
```
you shot get:

```
/usr/local/bin/dot
```
If it's not installed then please follow the installation instructions here https://graphviz.gitlab.io/

**Comment by colameo** [comment]
ok, the installation of dot was optional before v2.1.0. So, I'll change it back to make ti again optional. However, please note, that diagrams look slightly different. 

With Dot (Graphviz) installed:
![uml1](https://user-images.githubusercontent.com/629760/75688804-6a875c00-5ca0-11ea-90ee-a8c2924d5460.png)

Without Dot installed:
![uml2](https://user-images.githubusercontent.com/629760/75688819-71ae6a00-5ca0-11ea-9968-3807e80fb3f8.png)

Note the different aggregation line end in the one to many relation between EntityA and EntityB.

I'll keep this change for the next minor release open.
