### ISSUE TITLE
Should support custom field type in Visual Studio Code plugin

### ISSUE THREAD

**Issue by n5ken** [jhipster/jhipster-ide#335]
I appended some custom field types like Image, File etc to my generator, but once I add these types to jdl, the output keeps showing error message and Grapiviz not able to produce class diagram any more, but it work normal in jhipster online IDE, so can we ignore the field type check in VS Code? 

Example:
```jdl
entity LockGatewayModel {
  sn String required unique 
  name String
  note String
  // Does not support Image type
  image Image
}
```

**Comment by colameo** [comment]
> I appended some custom field types like Image, File etc to my generator,

can you send me the whole JDL file or the link to the repo?

**Comment by colameo** [comment]
...and btw a custom enhanced JDL type system is not supported. JDL Studio is different and less restrictive with syntax checks. You can also define a completely invalid JDL model which won't compile like this:
<img width="637" alt="Screenshot 2020-03-19 at 18 40 43" src="https://user-images.githubusercontent.com/629760/77097755-911ff380-6a11-11ea-8908-9b2984a77a12.png">

**Comment by n5ken** [comment]
Yes, JDL Studio will ignore type check and generate class diagram properly, that is what exactly I want, and VS Code not re-rendering diagram if format check fail. (I like the diagram style that generated by Grapiviz more than the one download from JDL Studio)

![image](https://user-images.githubusercontent.com/47604/77144188-2974b180-6ac0-11ea-94bf-22c1fafaa2b6.png)

PS: I tried to add image type to jdl.snippets.json, but with no luck. 

![image](https://user-images.githubusercontent.com/47604/77144247-4f9a5180-6ac0-11ea-8ea8-36a540523317.png)

**Comment by colameo** [comment]
Your snippet change won't help either...

Okay, let me explain (very) roughly how it works internally. The JH IDE is not "just an editor" with some nice syntax coloring and some sort of code completion functionality. You can compare it to a "mini IDE" which internally implements a compiler for a programming language (in our case for JDL) with the typically features like syntax coloring, syntax checks, semantic validation, code completion, searching for references, refactoring’s, validation and more.

So, if your model is invalid 'cause you "somehow" introduced new types then the internal "mechanism" will reject your model and nothing works (none, even diagram generation).

I’m closing this issue as there is nothing we can do here.
