### ISSUE TITLE
Missing app config options

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#337]

**Comment by crowne** [comment]
Looking at the latest version of [application_options.js](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/application_options.js) in jhipster-core, it looks like the options below should be added/updated in jhipster-ide.
Should these be added to ...jdl/config/JdlApplicationOptions.xtend or somewhere else?

- (add) blueprint
- (add) blueprints
- (update) cacheProvider #['caffeine', 'ehcache', 'hazelcast', 'infinispan', 'memcached', 'redis', 'no']
- (update) clientFramework #['angular', 'angularX', 'react', 'vuejs']
- (add) clientTheme
- (add) clientThemeVarient
- (add) creationTimestamp
- (update) databaseType #['sql', 'mongodb', 'cassandra', 'couchbase', 'neo4j', 'no']
- (add) embeddableLaunchScript
- (add) experimental
- (add) i18n
- (add) installModules
- (add) jhipsterVersion
- (add) npm
- (add) otherModules
- (add) packageFolder
- (add) reactive
- (add) rememberMeKey
- (update) searchEngine #['elasticsearch', 'couchbase', 'false']
- (add) skipGit
- (add) skipInstall
- (add) useNpm
