### ISSUE TITLE
Allow plugin install in Eclipse 2020-03

### ISSUE THREAD

**Issue by chrisbu** [jhipster/jhipster-ide#338]
**Is your feature request related to a problem? Please describe.**
Just updated eclipse to current version 2020-03 - jhipster IDE isn't marked as compatible.

**Describe the solution you'd like**
Update eclipse compatibility to include 2020-03 

**Describe alternatives you've considered**
Alternative is to keep using previous version of eclipse 2019-12

**Additional context**
I would do a PR, but can't find anything obvious in this repo that relates to eclipse versions, so I guess it's a setting in marketplace? (not an eclipse plugin developer, so I'm guessing).  I'm also guessing that there's work underway to update this plugin, so raising this issue to get a ping when it's done :)

**Comment by colameo** [comment]
a PR is not needed just create an issue as you did and I'll take care of it.

However, it's available now:
<img width="1027" alt="Screenshot 2020-04-02 at 15 36 43" src="https://user-images.githubusercontent.com/629760/78255857-246c2500-74f8-11ea-95ee-e7a382b3dc20.png">

Enjoy and don't forget to star this project ;-)
