### ISSUE TITLE
JDL Standalone Library for Java

### ISSUE THREAD

**Issue by stefan-ka** [jhipster/jhipster-ide#339]
Hello JHipster team

I have a question regarding your Xtext DSL... 

You do not publish the Xtext project as a library to a Maven repository, right? (only to a P2 repo for Eclipse.?) So that one could use the DSL project standalone, create a JDL model programmatically, and use the Xtext serializer to generate JDL code? I didn't find such a publication... Or did I miss something? Do you provide anything that would allow me to generate JDL code in my Java context?

Thanks for a short answer,
Stefan

**Comment by colameo** [comment]
Hi Stefan

This is not the official way of writing custom specific generators. 
See: https://www.jhipster.tech/modules/creating-a-blueprint/) for more information.

~Serano

**Comment by stefan-ka** [comment]
Hi @colameo 

Thanks for your answer! I'm however not 100% sure if I expressed my question well enough...

I don't want to write a custom generator for JHipster that generates code from JDL as input. I want to write a generator in my own application (https://contextmapper.org/ by the way) that generates JDL (your DSL) code as output, so that our users are able to use JHipster easily (convert our DDD models into a JDL file). Of course I could write my own serializer for your JDL DSL, but if I had the Xtext project available as maven dependency, I could simply use the serializer generated by Xtext (derived from your grammar: https://github.com/jhipster/jhipster-ide/blob/master/jdl/io.github.jhipster.jdl/src/io/github/jhipster/jdl/JDL.xtext) to generate JDL code. Implementing my own serializer for the JDL grammar would be much harder to maintain and to keep it up-to-date with you guys.

Thanks,
Stefan

**Comment by colameo** [comment]
Hi Stefan,
contact me directly.

I can explain you some (undocumented) features - but it is not part of this project as it would be in competition with the JHipster way of writing generators.

I'm closing this issue.

~Serano
