### ISSUE TITLE
Found groupable relationship "OneToOne"

### ISSUE THREAD

**Issue by tillias** [jhipster/jhipster-ide#341]
There are multiple errors "Found groupable relationship "OneToOne"

**Steps to reproduce the behavior:**
Install jhipster extension for VS Code
Create new *.jdl file
Paste sample jdl here from https://start.jhipster.tech/jdl-studio/

**Expected behavior**
Code is displayed without warnings / errors

**Screenshots**
![image](https://user-images.githubusercontent.com/753889/79960441-b0cd9000-8485-11ea-9cb3-5bd87155657f.png)
![image](https://user-images.githubusercontent.com/753889/79960467-b75c0780-8485-11ea-8d26-ad544611caa0.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - VS Code latest
 - 2.1.10

**Comment by colameo** [comment]
yes, this is correct and not a bug but a feature.

If you do not want linting warnings/errors you either refactor your jdl (in the above case by grouping all relations of the same type to one) or you disable this feature by adding at the beginning of your jdl file one of the following comment:
`//no-linting`
or
'// lint = false'

Of course, another option is you use JDL Studio which is less restrictive with validations and syntax checks ;-)
