### ISSUE TITLE
VSCode: "User" and "Authority" classes being added to renders

### ISSUE THREAD

**Issue by deftdawg** [jhipster/jhipster-ide#344]
**Describe the bug**

Why are there ``User`` and ``Authority`` classes being added to renders of JDLs with VS Code?

**To Reproduce**
1. Install vscode w/ jhipster-ide.jdl with Java and graphviz (tested on OSX)
2. create a test.jdl file with the following contents:

```
entity A
```
3. Save the file 
4. Open the generated test.png file

**Expected behavior**

I would expect only a box for ``entity A``, the way it renders on the [JDL Studio](https://start.jhipster.tech/jdl-studio/)

![image](https://user-images.githubusercontent.com/4991612/82829083-71c59c80-9e80-11ea-9985-e42c7ecbcee7.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/4991612/82828724-b866c700-9e7f-11ea-93e8-b90337c88e96.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14

**Comment by deftdawg** [comment]
It seems it is possible to override these classes at least, still this is messy:
![image](https://user-images.githubusercontent.com/4991612/82829490-6626a580-9e81-11ea-8d2d-40a544176ce3.png)

**Comment by colameo** [comment]
User and Authority are built-in types which are implicitly given.

**Comment by neshanjo** [comment]
> 
> 
> User and Authority are built-in types which are implicitly given.

That's only correct for the default project generation. If you use `--skip-user-management` when creating an app, these types are not generated (see https://www.jhipster.tech/creating-an-app/#3). I have such projects and also find it confusing that they are shown. Could you maybe add a VS Studio plugin configuration toggle to turn it off?

**Comment by colameo** [comment]
> > User and Authority are built-in types which are implicitly given.
> 
> That's only correct for the default project generation. If you use `--skip-user-management` when creating an app, these types are not generated (see https://www.jhipster.tech/creating-an-app/#3). I have such projects and also find it confusing that they are shown. Could you maybe add a VS Studio plugin configuration toggle to turn it off?

ok, agree, will changed.

**Comment by colameo** [comment]
ok, so you can use either
`
//skip-user-management 
`
or
`
//--skip-user-management 
`
at the very first line of your JDL to disable user management also in the JH IDE

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/629760/87469033-e44e2f80-c61a-11ea-916f-847b87a9b93c.png">

**Comment by colameo** [comment]
...please note, that you can also not refer to them:

<img width="479" alt="Screenshot 2020-07-14 at 21 48 16" src="https://user-images.githubusercontent.com/629760/87469570-c503d200-c61b-11ea-8938-da8cc245ef0d.png">

**Comment by colameo** [comment]
...but this of course cannot be handled by the JH IDE even if you have the //skip-user-management option set:

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/629760/87470046-7d317a80-c61c-11ea-97f2-04a0fdf6841b.png">

**Comment by neshanjo** [comment]
Thank you very much for your quick reply and implementation! 👍 👍 👍 

Just for interest: Are there other config parameter than `//--skip-user-management`, `//skip-user-management'`, `//lint=false`, `//no-linting`? It might be helpful to include some documentation in the main `README.md`.

I also realized that the VS code extension is working without having Graphviz installed on my machine. Is it now included with the extension?

**Comment by colameo** [comment]
> Just for interest: Are there other config parameter than `//--skip-user-management`, `//skip-user-management'`, `//lint=false`, `//no-linting`? It might be helpful to include some documentation in the main `README.md`.

No, there are no additional configuration options but of course it can be added.

BTW, instead of describing things in the README I've improved the content assist to propose at the very first line of a JDL all possible options. Note that these proposals are **only** available at the first line of a JDL file:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/629760/87591078-18435680-c6e8-11ea-990d-5dd35adf5de2.png">
