### ISSUE TITLE
PlantUML(⌥+D) doesn't open PlantUML preview.

### ISSUE THREAD

**Issue by kidylee** [jhipster/jhipster-ide#348]
**Describe the bug**
I'm using this extension in VSCode, it is able to generate png file, but not open the PlantUML preview window in VSCode as the Demo picture on the offcial website.

**To Reproduce**
1. Create a new jdl file in VSCode
2. Copy jdl from https://start.jhipster.tech/jdl-studio/
3. CMD+Shift+P -> PlantUML
4. No preview shows up.

**Expected behavior**
A PlantUML preview shows up on the right side window.

**Desktop (please complete the following information):**
 - OS: MAC
 - VSCode
 - Version 1.46.0

It is a very lovely tool, thanks!

**Comment by colameo** [comment]
Thanks for reporting this!

Microsoft deprecated an API which is used internally. However, I'm fixing it.

**Comment by colameo** [comment]
works again:

<img width="1219" alt="Screenshot 2020-06-15 at 09 48 08" src="https://user-images.githubusercontent.com/629760/84631297-6d275d80-aeed-11ea-8c4a-0bede158a8bc.png">
