### ISSUE TITLE
Cannot validate simple jdl file

### ISSUE THREAD

**Issue by bagage** [jhipster/jhipster-ide#351]
**Describe the bug**
The VSCode plugin raises various issues while using a valid JDL file, maybe related to #350?

**To Reproduce**
1. Create `jdl.jh` file with the following content:
    ```
	application {
		config {
			baseName app
		}
		entities Bueno
		dto Bueno with mapstruct
	}

	entity Bueno {
		name String required
	}

If you run `jhispter import-jdl jh.jdl` it works fine. However, the extension reindents improperly lines as:

```diff
application {
	config {
		baseName app
	}
	entities Bueno
-	dto Bueno with mapstruct
+ dto Bueno with mapstruct
}

entity Bueno {
	name String required
}
```

But also generates various errors:

> Couldn't resolve reference to JdlEntity 'Bueno'.
> missing '}' at 'dto'
> Couldn't resolve reference to JdlEntity 'Bueno'.
> missing EOF at '}'

**Expected behavior**
The code is left as is and no lint issue are shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/1451988/86784595-fd2a7400-c061-11ea-93d4-246977a80cae.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] VsCode 1.46.1 with plugin Jhipster JDL 2.2.0

**Additional context**

**Comment by colameo** [comment]
thanks for reporting. yes, was already in the pipeline as you stated. however, excellent issue report :-)
