### ISSUE TITLE
Words that happen to be keywords elsewhere should not be flagged as errors in names

### ISSUE THREAD

**Issue by deftdawg** [jhipster/jhipster-ide#360]
**Describe the bug**
Keywords that can be used as parts of names (i.e. config, entities) are valid as parts of names, however JDL IDE flags these as errors in the JDL.   

If they must be flagged perhaps consider changing this type of error to a warning instead.

**To Reproduce**
This JDL is valid in JDL, jhipster can generate packageName with "entities" as an element of the name.
```
application {
    config {
        packageName com.test.project.entities
    }
    entities *
}

DEFAULT_MIN_LENGTH = 2
DEFAULT_MAX_LENGTH = 50

entity Company {
    name String required minlength(DEFAULT_MIN_LENGTH)
    abbreviation String required 
    config String required
    entities String required
    logo String
} 
```

**Expected behavior**
No errors in the above file

**Comment by colameo** [comment]
yep, this is a known limitation which can be fixed.

**Comment by deftdawg** [comment]
Looking good!  Thanks!

Curious what the annotation `@Annto` does?  (I've not used annotations for anything yet)

**Comment by colameo** [comment]
> Looking good! Thanks!
> 
> Curious what the annotation `@Annto` does? (I've not used annotations for anything yet)

custom annotations - [see](https://www.jhipster.tech/jdl/options#custom-annotations)

**Comment by deftdawg** [comment]
@colameo looks like everything targeted for v2.3.1 is done, any idea when it would be released to be downloadable within VS-code?

**Comment by colameo** [comment]
this weekend
