### ISSUE TITLE
VSCode error

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-ide#37]
There seems to be an xtext server error when using vscode on the mac

[Error - 11:49:36 AM] Server initialization failed.
  Message: java.lang.IllegalArgumentException:Bad initialization request. rootPath must not be null.
  Code: -32603

**Comment by cbornet** [comment]
Is it from the source code + F5 or the plugin from the market place ?
I don't have a Mac so can you try to fix that ?

**Comment by colameo** [comment]
works for me. I had to update vc first and then install the plugin. maybe it's not compatible with an old version of vc.

![screen shot 2016-10-06 at 14 53 28](https://cloud.githubusercontent.com/assets/629760/19152949/b514c906-8bd4-11e6-9827-081c76f0a45d.png)

**Comment by jbadeau** [comment]
im on:
osx v10.12
vsc v1.5.3

<img width="1025" alt="screen shot 2016-10-06 at 16 03 32" src="https://cloud.githubusercontent.com/assets/152763/19155396/9963432c-8bde-11e6-80f0-88f3fdedf199.png">

**Comment by jbadeau** [comment]
Ill have a look this evening

**Comment by cbornet** [comment]
I didn't test drag n drop. I'll test on linux.

**Comment by cbornet** [comment]
I reproduce the issue when drag n dropping.
I'm going to see if the example xtext-vscode project also has the issue.

**Comment by cbornet** [comment]
I reproduce the issue with the [sample](https://github.com/TypeFox/languageserver-example) project so that's an xtext or vscode issue.

**Comment by colameo** [comment]
will make a bug report to our xtext team

**Comment by cbornet** [comment]
It also happens if you open by File -> Open File... (or CTRL+o)

**Comment by colameo** [comment]
..ok, I can reproduce it as well and found the part where it crashes:
![screen shot 2016-10-06 at 20 07 45](https://cloud.githubusercontent.com/assets/629760/19164521/953f47ba-8c00-11e6-8f59-078445ed2b61.png)

**Comment by colameo** [comment]
...I'll file a bug!

**Comment by cbornet** [comment]
I think the error is thrown [here](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend#L104)

**Comment by colameo** [comment]
yes, I agree ;-)

**Comment by colameo** [comment]
ok, known issue => https://github.com/eclipse/xtext-core/issues/57

**Comment by colameo** [comment]
...workaround: just open a folder before start using the JDL editor
