### ISSUE TITLE
LSP4J issue 

### ISSUE THREAD

**Issue by krisdierickx** [jhipster/jhipster-ide#374]
Fresh install of eclipse 2020-12 (4.18.0) on a windows environment
JHipster plugun 2.3.3

When I choose for a new JHipster project I got the message 

'The selected wizard could not be started.
org/eclipse/lsp4j/Range (occurred in io.github.jhipster.jdl.ui.JDLExecutableExtensionFactory)
org/eclipse/lsp4j/Range'

Seems to be an issue that occured also with earlier versions but that was fixed at that moment: https://github.com/jhipster/jhipster-ide/issues/201

**Comment by colameo** [comment]
eclipse 2020-12 (4.18.x) is currently not supported:

![image](https://user-images.githubusercontent.com/629760/105626190-910d3300-5e2e-11eb-8c87-333a533a84d0.png)

so, downgrade to 4.17 which works as you can see below:
![image](https://user-images.githubusercontent.com/629760/105626378-7d160100-5e2f-11eb-83d0-81d0e5936f45.png)

however, I will build a new maintenance release
