### ISSUE TITLE
VS Code Studio: ServerLauncher process using high CPU

### ISSUE THREAD

**Issue by smunir** [jhipster/jhipster-ide#379]
Opending JDL file in VS Code Studio launches ServerLauncher process which consumes almost 100% CPU.

**To Reproduce**
1. Install Jhipster extension in VS Code
2. Open JDL file
3. Check activity monitor for ServerLauncher process
4. Check that ServerLauncher process is consuming high CPU

**Expected behavior**
ServerLauncher should not consume this much CPU.

**Screenshots**
<img width="817" alt="image" src="https://user-images.githubusercontent.com/4279499/112323607-c53c8d00-8cd3-11eb-84a7-4be0f1ed3ea6.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version: 11.2.1

**Comment by colameo** [comment]
yes, sure, but after it has started it takes nearly no cpu power:

<img width="935" alt="Screenshot 2021-03-24 at 16 26 09" src="https://user-images.githubusercontent.com/629760/112336892-bf3bb180-8cbd-11eb-88b2-70af641fd766.png">

**Comment by smunir** [comment]
It kinda gets stuck and doesn't start in my machine and keeps taking 101% CPU. I need to work on a JDL and my Mac is getting too hot because of this :-(

**Comment by colameo** [comment]
...hm, strange, which JDK version do you use?

you need a Java 11 JDK:

![image](https://user-images.githubusercontent.com/629760/112377618-44d35780-8ce6-11eb-9008-869bc71e2f39.png)

**Comment by smunir** [comment]
I am using https://sdkman.io for managing JDK Installations and had java.home in settings.json set to _/Users/shahzad/.sdkman/candidates/java/current_. I updated this to _/Users/shahzad/.sdkman/candidates/java/11.0.2-open_ and now I can't see ServerLauncher process in activity monitor. Even setting it back to _/Users/shahzad/.sdkman/candidates/java/current_ didn't make any difference. I can see JDK Language Server started! in status bar, suggestions/templates are working fine, not sure what issues I could face but CPU and fan are happy now. Should I close the issue if we don't need to investigate absence of ServerLauncher in processes list?

**Comment by colameo** [comment]
if you do not see the ServerLauncher process anymore then it's not working at all... 

I am using java over sdkman on a macbook and have no problems.

![image](https://user-images.githubusercontent.com/629760/112463420-81dd2f80-8d62-11eb-96fd-99ded7ab0186.png)

Try this version: AdoptOpenJDK / 11.0.10.hs-adpt

**Comment by smunir** [comment]
It started a few hours ago again with same CPU percentage. As you suggested I switched to AdoptOpenJDK / 11.0.10.hs-adpt and now it's started taking only 0.2% CPU. We can conclude that this was because of Open JDK. Thanks for your help.
