### ISSUE TITLE
Unable to create new project using wizard

### ISSUE THREAD

**Issue by nvg** [jhipster/jhipster-ide#385]
**Describe the bug**

When attempting to start a new project the following error occurs on Win:

```
The selected wizard could not be started.
io.github.jhipster.jdl.ui.wizard.JDLNewProjectWizardEnhanced cannot be found by io.github.jhipster.jdl.ui_2.4.0 (occurred in io.github.jhipster.jdl.ui.JDLExecutableExtensionFactory)
io.github.jhipster.jdl.ui.wizard.JDLNewProjectWizardEnhanced cannot be found by io.github.jhipster.jdl.ui_2.4.0
```

**To Reproduce**
1. Download the latest eclipse (eclipse-jee-2021-09-R-win32-x86_64)
2. Install XText and EMF to Graphviz from the market place (without those jhipster IDE won't even install - which is another bug IMHO)
3. Install jhipster IDE
4. Click "start new project" > jhipster and observe the error

**Expected behavior**
Expect to be able to create a project

**Screenshots**
![image](https://user-images.githubusercontent.com/718122/135305526-d98e1e82-7ea3-4c51-915a-1eb612948533.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java 17
 - JHipster Version 2.4.0

**Additional context**

**Comment by colameo** [comment]
eclipse 2021-09 (4.21.0) is not yet supported (i've just deactivated to prevent further installations).

**Comment by colameo** [comment]
duplicate of #386

**Comment by nvg** [comment]
Thank you for taking a look! Closing as duplicate.
