### ISSUE TITLE
could not preview UML using visual studio code on windows 10，saying cannot read properties of undefined(reading 'documents') 

### ISSUE THREAD

**Issue by scyllor** [jhipster/jhipster-ide#392]
**Describe the bug**
could not preview UML using visual studio code on windows 10，saying “cannot read properties of undefined(reading 'documents') ”
**To Reproduce**
1. open vscode on windows 10
2. type sample entity
3. open command palette, and type "Plant Uml"
4. See a broken picture with 0B

**Expected behavior**
a UML graph
**Screenshots**
![image](https://user-images.githubusercontent.com/2325287/167673449-477fb9c8-1a4f-4886-88d1-1d3bc6096780.png)
![image](https://user-images.githubusercontent.com/2325287/167673487-5994dd0b-9f34-45af-89d8-da6bed138e9c.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [edge]
 - Version [vscode 1.67]
Version: 1.67.0 (system setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
**Additional context**

**Comment by colameo** [comment]
have you installed [graphviz](https://graphviz.org/download/)? 

![image](https://user-images.githubusercontent.com/629760/167830258-114fb746-10be-43b1-b425-8bbe39c69dd0.png)

**Comment by scyllor** [comment]
yes, already installed the latest version and i can work around it with eclipse now.
![image](https://user-images.githubusercontent.com/2325287/167855099-ba0c2629-3cbb-46d6-8e07-bf972313480c.png)

**Comment by colameo** [comment]
im closing this issue as it not reproducable
