### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-ide#42]
@colameo @deepu105 @jdubois

Hello guys this issue is to track:
- when we do a 0.1.0 release of jdl-ide
- what features should be in

It would be nice to introduce it with a new version of jhipster. Any timeline of the next jhipster releases? I also think we should release on the new version of xtext https://github.com/jhipster/jhipster-ide/issues/28 which brings official support for LSP which is the basis of the vscode integration.

So earliest would be sometime after October 18, 2016 (xtext 2.11 release date)
### common
- Move plantuml code to its own module https://github.com/jhipster/jhipster-ide/issues/34
- align eclipse and idea templates with vscode snippits https://github.com/jhipster/jhipster-ide/issues/41
- Add validations and make content assist nicer https://github.com/jhipster/jhipster-ide/issues/24
### eclipse
- add cardinality to uml diagram https://github.com/jhipster/jhipster-ide/issues/40
- test integration
### intellij
- test integration
### vscode
- VSCode error https://github.com/jhipster/jhipster-ide/issues/37
- test integration
### documentation
- publish
- document instructions on installing (should be small)

**Comment by colameo** [comment]
I would suggest to improve the xtext "frontend" (validation, scoping, CA etc.) as well.
There is almost no logic implemented and it feels not so good...
So please add #24 to the list of eclipse issues

**Comment by colameo** [comment]
...hm, sorry, it is already in the common list ;-)

**Comment by jdubois** [comment]
Does this means the 1.0.0 release is ready? Don't hesitate to ping me, so I can communicate on Twitter, etc

**Comment by colameo** [comment]
We are close to finish our first release (at least the eclipse version). We will inform you, as soon we are ready.

**Comment by jdubois** [comment]
@colameo by the way, I didn't follow for the website, are you able to do a specific page on https://github.com/jhipster/jhipster.github.io ? Do you need my help?

**Comment by colameo** [comment]
@jdubois would be nice if you could help ;-) have a look to [1]

[1] https://jhipster.github.io/jhipster-ide/

**Comment by deepu105** [comment]
It would be nice if the page can follow the documentation site template.
Are you autogenerating the page?

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
@colameo yes it's very easy, can you add another page here:

https://github.com/jhipster/jhipster.github.io/tree/master/pages

- The page would be "jhipster-ide.md"
- The images would be [here](https://github.com/jhipster/jhipster.github.io/tree/master/images)

Then I'll check if it's all fine, and add it to the menu (it would probably go to the "tools" section). The great thing is that you will then be automatically in our sitemap file, so you will get indexed. I'll give you access to our Google Analytics account so you can track the result.
