### ISSUE TITLE
make JDL lang less "noise"

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#44]
I would like to make JDL's grammar less "noise" and redefine certain tokens (e.g. ',') as optional.

Note: we wouldn't break the JDL spec, as the tokens above will still be in the grammar. 

Do you agree?

**Comment by jbadeau** [comment]
Sounds ok to me but not sure if their parsers wont fall over if no , are present

**Comment by colameo** [comment]
...that's really a point... let's wait until we know the impact

**Comment by MathieuAA** [comment]
It could break everything =) 
Where would you remove `,` chars? In relationships and/or in field definitions?
