### ISSUE TITLE
Replace icons with better looking ones

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#55]
Create nice looking icons in => jhipster-ide/io.github.jhipster.jdl.ui/icons

**Comment by jbadeau** [comment]
check it out:
<img width="705" alt="screen shot 2016-10-11 at 01 23 24" src="https://cloud.githubusercontent.com/assets/152763/19254180/64442d3e-8f51-11e6-9b8f-b12a47d0091a.png">

**Comment by colameo** [comment]
Cool!

**Comment by colameo** [comment]
...did you retry to push on github? Strange that since we moved to jhipster we cannot push changes from eclipse anymore, isn't it? However, with SourceTree it works ... ;-)

**Comment by colameo** [comment]
@jbadeau could you please merge your changes to master?

**Comment by jbadeau** [comment]
Yes I will merge this evening

**Comment by jbadeau** [comment]
I also hVe worked on the web ui. It's an angular app now
