### ISSUE TITLE
publish p2 repository web

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-ide#6]

**Comment by jbadeau** [comment]
@jdubois @deepu105 I would liketo make a dryrun release of the plug-ins. Where shall the hosting for the files be? Bintray or somewhere in the jhipster site? Do you guys have a standard for that?

**Comment by jdubois** [comment]
We are only distributing NPM packages for the moment, so we haven't done this kind of thing yet.

I just created a "jhipster" organization on bintray, and I have added a Maven repo for JHipster IDE:
https://bintray.com/jhipster/jhipster-ide

-> does this sound good to you? If yes, I will of course give you access to it.

**Comment by jbadeau** [comment]
Yes, I think that should work for now. Perhaps it looks more professional if it's on the website at some point but for now its easiest to publish to bintray. 

I also saw that you haven't applied for jhipster in maven central. We will most likely need to publish jars there.

**Comment by jdubois** [comment]
Oh yes, we also publish on the "main website" using the GitHub releases, like at https://github.com/jhipster/jhipster-app/releases

I'm also going to look at Maven Central, but last time I worked with them (more than 10 years ago!!) it wasn't very good.

**Comment by jdubois** [comment]
OK Maven Central is still a mess... Let's use Bintray for the moment, we'll do this afterwards if needed.

**Comment by jdubois** [comment]
BTW I asked for a Maven Central groupId for JHipster, we'll see how it works: https://issues.sonatype.org/browse/OSSRH-25366

**Comment by colameo** [comment]
depends on #67

**Comment by colameo** [comment]
https://dl.bintray.com/colameo/jh-ide/
