### ISSUE TITLE
Integration of Xdocker IDE in JHipster-IDE

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#72]
@cbornet @deepu105 @jbadeau @jdubois @MathieuAA 

A couple of years ago I started developing with Java, Xtext and Eclipse an IDE to manage Docker technology. The product is called Xdocker which stands for eXtendable Docker IDE.

The main reason was because there was (and actually from my point of view, it is still the situation) no good editor in Eclipse for Dockerfiles. Beside of that I also wanted a better integration in Eclipse for building docker images, run containers, browse running instances and manage them via an IDE in a quick and easy way.  Xdocker allows developers also to add more features on the DSL and even to write own generators.

In addition to that I've developed a web application with Xtext for web and Eclipse Scout (a web application framework written in Java/JS) as well. Most of the code is written in Xtend (our GPL programming language made with Xtext). The code is not public yet and I thought to give it to an open source project/organization like JHipster. 

I really like what we are doing in this project, so I thought to myself as JHipster also uses Docker for application development, we could integrate as part of the jhipster-ide project Xdocker IDE features.

Here a link to my presentation last year at Eclipse DemoCamp in Zurich => https://wiki.eclipse.org/images/7/70/ScoutXtextDocker.pdf

What do you thing about that? Please vote/comment.

/Serano

**Comment by MathieuAA** [comment]
That could be interesting. However, I doubt a lot of JHipsters know of Xtend but from what I see, it's really easy to pick up and do something with. So for me it's a **+1** (as long as we don't do GWT stuff, like we can see [here](http://www.eclipse.org/xtend/).

**Comment by PierreBesson** [comment]
Hi @serano It is indeed cool work but I have trouble thinking of a use case for JHipster. 
As far as I understand it is a DSL to access the docker API but we already have Java libraries for that. What advantages does it have ?

As you might know we already provide a way to contenerize app, for this we provide a simple dockerfile and use the spotify maven plugin / grade scripts.
For us what is more interesting is `docker-compose` so that we can start multiple docker container（for example databases, microservices) at once.
Does your DSL allows to do that ?
Anyway you are still free to build your own module so that you can convince us how awesome this is :wink:...

**Comment by colameo** [comment]
@PierreBesson No it is not "just a DSL" ;-) but rather a set of plugins to manage Docker inside an IDE. Beside of the Dockerfile editor feature, users (application developers) could build docker images, create/run/stop containers etc. from the JHipster generated Dockerfile(s) inside an IDE (some of the Eclipse features could be made available also for VS code/IntelliJ). Of course we could also add some more "JHipster-related stuff" and also integrate docker-compose (or any other docker functionalities/utils).

**Comment by PierreBesson** [comment]
I see, it seems to be very powerful. Potentially quite interesting in our approach to simplify microservice developement.
Especially if it supports multiple IDE, we could try to run some experiments. When will you release the code for XDocker ?

**Comment by jdubois** [comment]
Our first focus is the command line, as obviously everyone can run it... Then of course, having higher-level tools in sub-projects is much easier for a lot of people, and having a new sub-project doesn't really cost us anything.
Then this is outside of my "confort zone": I have never used such a tool, and I don't see right know how we would use it. I would need time to review it, and see the use cases in "real life".
As long as we haven't released JHipster 4, I don't think I can spend the time necessary: I just have too much work at the moment. But if everyone else want it, it's cool for me to add a new sub-project: once again, it doesn' t cost us anything!

**Comment by colameo** [comment]
ok, for those who answered, thanks for the feedbacks ;-)

The question is now, shall we integrate Xdocker to the jhipster-ide sub-project or shall we create a new one (jhipster/jhipster-docker-ide, jhipster/jhipster-xdocker or something like that) ?

**Comment by colameo** [comment]
make an example on how to use xdocker in combination with jhipster
