### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-ide#80]
I've seen you set up a specific web page at https://jhipster.github.io/jhipster-ide/

- It should better be a page in https://github.com/jhipster/jhipster.github.io so it benefits from our SEO (it would be included in our sitemap.xml for instance)
- I would like to demo this next Monday at Devoxx, but I can't find how to install it on Intellij IDEA or Eclipse. Could you provide a guide for newbies like me?

**Comment by colameo** [comment]
Nice to hear that you want to make a demo :-) 

Can we split these two tasks and maybe you can prepare/add a dummy web page to the main page and I will take care about the installation stuff?

**Comment by jdubois** [comment]
Yes I'll integrate it into the main site, but that's easy: just copy a page like https://github.com/jhipster/jhipster.github.io/blob/master/pages/jhipster-app.md

And then add your text/images etc

I will then add the menu (in "tools"? Is that fine with you?) and merge everything.

BTW we're starting to have quite a number of tools, we're going to need some introduction explaining those, but I'll do it afterwards.

**Comment by PierreBesson** [comment]
@jdubois I'm thinking that maybe it's not necessary to add this to the main site. It can be managed from here and linked to from the site. It is actually already available at https://jhipster.github.io/jhipster-ide

**Comment by jdubois** [comment]
@PierreBesson yes I know, but then it can't be added in our sitemap.xml, which isn't good for Google...
Besides I'd like to have the whole documentation versioned and archived, and for this I need to tag everything.

**Comment by colameo** [comment]
@jdubois I know it's easy, but my time is very limited (I have a company + employees to take care... ;-)).

Just for a quick try, checkout the project and from the parent call maven as follows:
$ mvn clean package **-Pproduct**

Then start eclipse and install from local folder pointing to: **./io.github.jhipster.jdl.releng/target/build/final**

We need to upload this update site to a repo hosting solution like bintray ... if someone could help on that, I would really appreciate...

**Comment by colameo** [comment]
...so, I created roughly a bintray package => https://dl.bintray.com/colameo/jhipster-ide/

you need eclipse neon + http://www.graphviz.org installed on your machine.

can you try to install it?

**Comment by jdubois** [comment]
Yes and it's working great!
I'm adding this at slide 68 on my Devoxx presentation at:
https://docs.google.com/presentation/d/1qUSulPZ0l21SXJYnhrRvJqIAp1YYJwvcXPX0Ekye9Io/edit?usp=sharing

Don't hesitate to comment!

**Comment by cbornet** [comment]
@jdubois if you also want to demo vscode, there is a "cbornet.jdl" extension. I can try to merge the latest developpements from the master if you want (such as User entity management).

**Comment by jdubois** [comment]
thanks @cbornet but here I have something working for my demo, so that's good for me. I don't want to go through all the trouble of testing it all again :-)

**Comment by colameo** [comment]
...finally, a quick solution for the moment:

![eclipseupdatesite](https://cloud.githubusercontent.com/assets/629760/19867970/4b572ea6-9fa6-11e6-8357-e45d658088be.png)

**Comment by colameo** [comment]
...sorry, need to republish

**Comment by colameo** [comment]
Have a look => https://jhipster.github.io/jhipster-ide

**Comment by PierreBesson** [comment]
Very nice gif. @jdubois you should post this gif on twitter. Here is the optimized version of the GIF (9mb vs original 24mb)
![eclipse](https://cloud.githubusercontent.com/assets/513471/20634981/3829e534-b357-11e6-865c-48efefbd2c29.gif)

**Comment by jdubois** [comment]
@PierreBesson can you tweet it and mention java_hipster ? I'll RT you

**Comment by colameo** [comment]
@cbornet can you please also add an installation guide or screen cast for VSC?

**Comment by cbornet** [comment]
@colameo yes but that means we should publish an official extension. Currently it's under my name...

**Comment by cbornet** [comment]
I'll try to merge the master on vscode branch to get the latest features.

**Comment by colameo** [comment]
@cbornet please take release branch (https://github.com/jhipster/jhipster-ide/tree/release/v1.0.0) as master is already on 1.1.0

**Comment by cbornet** [comment]
Ok. No problem.
