### ISSUE TITLE
JHipster IDE - Eclipse plugin repository URL appears to be down

### ISSUE THREAD

**Issue by shinusuresh** [jhipster/jhipster-ide#95]
Eclipse plugin repository URL mentioned in JHipster-IDE documentation appears to be down. 
[https://dl.bintray.com/colameo/jhipster-ide/](https://dl.bintray.com/colameo/jhipster-ide/)

I am seeing connection exceptions in my STS Ide while trying to install.

**Comment by colameo** [comment]
<img width="499" alt="screen shot 2016-11-28 at 14 07 27" src="https://cloud.githubusercontent.com/assets/629760/20669371/19f92e52-b574-11e6-9217-d49ff6fd43d9.png">

...works for me, can you retry?

**Comment by shinusuresh** [comment]
My bad. I was behind a corporate proxy which denied this page.
Plugin repo is working fine. No issues.
