### ISSUE TITLE
Move update site to an own jhipster ide bintray

### ISSUE THREAD

**Issue by colameo** [jhipster/jhipster-ide#96]

**Comment by colameo** [comment]
@jdubois can you add us to jhipster bintray organization? I want to create official jhipster-ide repositories (p2, maven, ...). thks

**Comment by colameo** [comment]
us = @colameo, @jbadeau ...

**Comment by jdubois** [comment]
I need to have a look at how bintray works -> I'll do this tomorrow

**Comment by jdubois** [comment]
You should both have received invitation -> tell me if that's not the case!!

As we are on the free version of Bintray, that means you will have publish rights on all our binaries: at the moment jhipster-ide is the only one, but that shouldn't last, so use those permissions wisely, and protect your account :-)

**Comment by colameo** [comment]
Thanks for adding us to the jhipster organization in bintray. The type of repo to host p2 artifacts must be "Generic" and not maven:
![screen shot 2016-12-13 at 12 30 58](https://cloud.githubusercontent.com/assets/629760/21138830/342492cc-c130-11e6-99f4-af623b89fd3b.png)

Can you give one of us the rights to add repositories or just create one of type generic?

**Comment by colameo** [comment]
![screen shot 2016-12-13 at 12 40 15](https://cloud.githubusercontent.com/assets/629760/21139049/55d7ca6e-c131-11e6-8d45-3cbb11087b5f.png)

**Comment by jdubois** [comment]
I'm going to have a look at this now.
For [jhipster/jhipster](https://github.com/jhipster/jhipster) I'm directly sending my files to Sonatype, without going through bintray: I don't have all this fancy UI, but on the other hand I don't depend on a third-party company, with some limitations as we are limited to their "OSS" offer. Maybe you could have a look at this too?

**Comment by jdubois** [comment]
It should be OK now, ping me if you still have an issue!
